### ISSUE TITLE
NFT #0: get wallet address for payments (artist or MOI?)

### ISSUE THREAD

**Issue by hollygrimm** [PrisonArt/restore#16]

**Comment by andytudhope** [comment]
Technically, this is a question of who the `creator` address is set to when we create the first auction.

The contracts expect PA `payment` to receive the artists' portion, exchange it to USD and settle their LFOs on their behalf. So, technically, the `creator` address should be set to MOI to receive the 40%. This makes me realise that naming it `creator` was misleading - my apologies: it should be `community` or `partner` or something like that. Naming things huh...

My suggestion here is that we use the FTX account that was set up as the address for MOI, take the 50% that will be sent to payment address, exchange it, pay what we can of Sammie's debts and get the receipts for that ourselves, as it is important that this is handled by PA, both for easier logistics, and for reasons of precedent and clarity for future projects.
