### ISSUE TITLE
Re-query subgraph for bids until bid with same value from 'AuctionBid' event appears

### ISSUE THREAD

**Issue by hollygrimm** [PrisonArt/restore#5]

**Comment by hollygrimm** [comment]
Dear @andytudhope, can you please create a new Rinkeby auction and check if the bids are loading as expected? I deployed code to reload the subgraph up to five times, every five seconds, until the bid is loaded.

**Comment by andytudhope** [comment]
Done and done - it works well afaict and you are a genius :pray:
