### ISSUE TITLE
Proof of Transfer link and LFO Table Updates

### ISSUE THREAD

**Issue by hollygrimm** [PrisonArt/restore#8]

**Comment by hollygrimm** [comment]
![Image](https://user-images.githubusercontent.com/28874939/169706856-88bd6c19-5177-4fb1-89de-596e91d5d41c.png)

**Comment by hollygrimm** [comment]
@andytudhope Can you rebuild the subgraph and deploy to rinkeby? I've added the hash of the transfer transaction to the NFT Entity:
https://github.com/PrisonArt/restore/commit/2bfe4675ebda175f6679ad24fcfdc836f68b4a10#diff-8bf33045d6e6d9b1d66f2ec017979e701d8b2d21021e4f652005da43aa7a41aa

**Comment by andytudhope** [comment]
https://github.com/PrisonArt/restore/commit/8e29b4b5a4983c43e237ffc99af6781d86e703ea

:heart:
